language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
    - TOXENV=test
    - TOXENV=install
    - TOXENV=flasksqlalchemy
before_install:
    - sudo apt-get -qq install graphviz > /dev/null
    - travis_retry pip install tox flake8
install: true
script:
    - flake8 .
    - travis_retry tox
after_success:
    - coveralls
