# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# https://github.com/ymyzk/tox-gh-actions

name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    services:
      eralchemy-db:
        image: postgres:alpine
        env:
          POSTGRES_DB: eralchemy
          POSTGRES_PASSWORD: eralchemy
          POSTGRES_PORT: 5432
          POSTGRES_USER: eralchemy
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up pg-client
        run: |
          sudo apt-get update
          sudo apt-get -qq install graphviz python-dev libgraphviz-dev pkg-config postgresql-client

      - name: Setup database
        run: psql -h localhost -U eralchemy -c 'CREATE SCHEMA eralchemy_test;'
        env:
          PGPASSWORD: eralchemy

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

  #     - name: Lint with flake8
  #       run: |
  #         # stop the build if there are Python syntax errors or undefined names
  #         flake8 .
      - name: Test with pytest
        run: tox
      
      - name: Install python dependencies
        run: python -m pip install isort black mypy

      - name: Run isort check
        run: isort --check eralchemy2

      - name: Run black check
        run: black --check eralchemy2

      #- name: Run mypy
      #  run: mypy eralchemy2
